apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
      - name: practice-app
        image: nginx
        ports:
        - containerPort: 80
